### ISSUE TITLE
Can't get to the options section

### ISSUE THREAD

**Issue by Fristi10** [ollo69/ha-samsungtv-smart#122]
In the documentation their is the following:
_From the Home Assistant front-end, navigate to 'Configuration' then 'Integrations'. Identify the 'SamsungTV Smart' integration configured for your TV and click the OPTIONS button._

I can't get to find the OPTIONS button when I follow these steps:

![Screenshot 2022-01-11 at 16 33 50](https://user-images.githubusercontent.com/71131752/148973853-e1152325-992e-410d-9b83-43ffe579e398.png)

 - Environment : HA in docker 
 - Home Assistant version installed: 2021.12.1
 - Component version installed: 0.4.10
 - TV model: The frame

**Comment by ollo69** [comment]
You are not using `SamsungTV Smart` (this integration) but `Samsung Smart TV` that is the native HA Samsung TV integration. I understand that naming is confusing, but that's it!
Install and configure the correct integration (obviously before remove the native one) and you will see OPTIONS button.
I close this issue because not pertinent, open a new one after configuring the right integration if you still ha problems.👍

**Comment by Fristi10** [comment]
@ollo69 many thnx
