### ISSUE TITLE
Delay in updating attributes

### ISSUE THREAD

**Issue by mendoncart** [ollo69/ha-samsungtv-smart#123]
**Describe the bug**
It's taking 10 seconds for the is_volume_muted attribute to be updated.
Also, I can't use it as trigger in automations. I don't know why, but it doesn't trigger.

**Expected behavior**
Expected to have a quicker update of the attribute.

**Screenshots**
Attribute:
![image](https://user-images.githubusercontent.com/62950083/149022923-73fa70d9-3752-495e-a56b-e0ea53e20ec6.png)

Automation Trigger:
![image](https://user-images.githubusercontent.com/62950083/149022818-d528883b-e22f-4ca9-ab1f-15264db9f0cc.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): I don't know exactly but is running on virtualbox
 - Home Assistant version installed: Home Assistant 2021.12.6
 - Component version installed: Latest (launched today)
 - Last know working version: None
 - TV model: UN75TU8000GXZD

**Additional context**
Since I can't detect if the tv is paused or playing, I thought in using the mute button, so I'd mute the tv, and the automation would pause the media, and turn on the lights. 
But I'm having two problems: 
1.  The attribute update is too slow for this. Is there a way to make it quicker?
2. Using True as a condition in a automation, doesn't work, even wher the attribute updates to true. Should I use a different value as a trigger?

**Comment by ollo69** [comment]
> 1. The attribute update is too slow for this. Is there a way to make it quicker?

This integration is base on device polling (there are no event coming from the TV) and polling period is 15 seconds. It is not possible to use an higher rate, this would break HA state machine.


> 2. Using True as a condition in a automation, doesn't work, even wher the attribute updates to true. Should I use a different value as a trigger?

It should work, but if not is not a problem related to integration, Try with this:

1) remove the `From` parameter, leave only `To`
2) try using `False` (first letter uppercase) or `off`. If does not work ask help to HA community or open a issue to HA core.

Please close this issue because there is nothing to fix here.👍

**Comment by mendoncart** [comment]
Thanks for the help, I'll try it.
Sorry to open an issue with unrelated problems.
And thank you for taking your time to developing this integration so helpful, and responding my silly question.
Take care!
