### ISSUE TITLE
List of entity to Power ON/OFF not working

### ISSUE THREAD

**Issue by ripburger** [ollo69/ha-samsungtv-smart#133]
Love the integration! No matter what I try, List of entity to Power ON with TV and List of entity to Power OFF with TV never seem to trigger.

Is this a known issue, or am I doing something wrong?

**Comment by ollo69** [comment]
No known issue, and it works for me. Could you provide more details? Please extract and attach diagnostic infos.

**Comment by ripburger** [comment]
Thanks for the reply! I have found out what the problem is: I have two media players I'd like to switch on when the TV is on. One does work with the homeassistant.turn_on command, the other one apparantly doesn't.

For some reason, if one isn't responding to the homeassistant.turn_on command, then none of the selected media players is switched on.

**Comment by ripburger** [comment]
No, no errors show up in the LOG. I guess it's not an error per se, it's just that the entity (a Philips Hue Syncbox) doesn't respond to the homeassistant.turn_on command and doesn't throw an error.

**Comment by ollo69** [comment]
I take a look to the code. Because I'm calling HA method to run services in background and there are no error to catch, there is nothing I can do integration side. You should eventually open an issue HA side or just not include in the list devices that doesn't respond to turn_on command.
Close this issue.
