### ISSUE TITLE
rtsp:// stream

### ISSUE THREAD

**Issue by TokarevSergey** [ollo69/ha-samsungtv-smart#144]
Good afternoon. Tell me, is the broadcast of rtsp IP cameras supported in your automation, and if so, how? I am unable to launch. Help. Thanks.

**Comment by ollo69** [comment]
Not at this moment. Are you able to see rtsp camera on your TV? If yes how (e.g. using TV browser or another app)?

**Comment by ustrucx** [comment]
Thanks for the great integration! 

Does this mean when I select the TV on Hass's Media UI and try to play my camera with the TV as target it is expected it won't work? I ask because I tried almost everything (other integrations, DLNA...) and it wont work, then I tried the below, non rtsp URL, and still no luck. 

I could not find confirmation whether anyone has this working, and the videos on youtube with automations showing the camera feed on TV do not say which TV brand it is...so I seen it working but can't tell which TV they used.

I just wanna make sure it just isn't possible on Samsung at the moment so I can stop trying and move on ¯\_(シ)_/¯ 

```
{
  "entity_id": "media_player.samsung_tv_bedroom",
  "media_content_type": "url",
  "media_content_id": "http://192.168.15.6:8123/api/camera_proxy_stream/camera.unnamed_my_camera_1?token=12345",
}
```

**Comment by TokarevSergey** [comment]
Добрый день. Tizen tv не работает с rtsp камерами. :(

пн, 21 мар. 2022 г., 22:50 ollo69 ***@***.***>:

**Comment by vmonkey** [comment]
> Not at this moment. Are you able to see rtsp camera on your TV? If yes how (e.g. using TV browser or another app)?

I would definitely love this feature too. I was able to get my webcam streams working on UE50TU7172 by using  SS-IPTV app there (not present in the tizen app repository), and rtsp through http streams (on my reolink cameras, these are in the form http://192.168.x.y/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=USER&password=PASSWORD)

**Comment by MicheleMercuri** [comment]
On my Samsung UE55...7170 I can stream NVR cameras (nvr dahua also integrated HA) by selecting the cameras from "media sources"  . 

![IMG_20221006_215932](https://user-images.githubusercontent.com/97225788/194407135-315956d7-a20b-4e99-ac62-bf6f25e3cbbb.jpg)
