### ISSUE TITLE
Error after upgrade of HA to 2022.07.0

### ISSUE THREAD

**Issue by KHV8** [ollo69/ha-samsungtv-smart#172]
After upgrade to 2022.07.0 I get the following error when checking the configuration. Everything was working in 2022.06.7.

Platform error media_player.samsungtv_tizen - Requirements for samsungtv_tizen not found: ['numpy==1.21.1'].

During restart I get the same error message in the HA logs.

My configuration looks like this, quite straight forward
`media_player:
  - platform: samsungtv_tizen
    host: 192.168.0.106
    name: Stue TV`

**Comment by ollo69** [comment]
This is `samsungtv_smart`, your issue is related to `samsungtv_tizen` that is a different integration and is hard pinning `numpy`, reason for which you are receiving this error.
If you want you can install this integration that do not have this issue, but before you need to remove `samsungtv_tizen`.

Closing this.
