### ISSUE TITLE
Advanced option configuration fails to display.

### ISSUE THREAD

**Issue by 0n3man** [ollo69/ha-samsungtv-smart#174]
**Describe the bug**
Checking advanced options on the integration configuration page gives the error

User input malformed: Not a list for dictionary value @ data['sync_turn_off']

**Expected behavior**
Advanced options screen is supposed to pop up.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Supervised install on Debian 11.
 - Home Assistant version installed: 2022.7.6 (Supervisor 2022.07.0 Frontend 20220707.1 - latest)
 - Component version installed:  0.7.4
 - Last know working version: Just stated using so I'm not sure if it ever worked.
 - TV model: Samsung UN55NU800D

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by StarRaven** [comment]
I had the exact same issue, maybe the following methods could temporarily work (I don't really remember if I did any other things between those steps)
0. the problem is because of ['sync_turn_off'] is null instead of a list (I think)
1. click 'List of entity to Power OFF with TV', select a random entity, and de-select it
2. do the exact same things for the 'List of entity to Power ON with TV'
3. tick show advanced options
4. click submit

**Comment by 0n3man** [comment]
You suggestion of enabling and disabling item to power on and off did allow me to bring up the menu, however then when I tried to adjust the advance options I got a similar error: User input malformed: value must be one of .....,  Here I think it is looking for me to selection something from the "Binary sensor to help detect power state".  Only issue here is if I select something from the list it doesn't appear there is an option to un-select the item and I don't have a binary sensor that would make sense for helping to detect power on state.

**Comment by ollo69** [comment]
This error was caused by some changes in HA UI and should be fixed in last release.

**Comment by 0n3man** [comment]
That fixed it.  Thanks for the great work.
