### ISSUE TITLE
Error: Wrong SmartThings token.

### ISSUE THREAD

**Issue by Krocko** [ollo69/ha-samsungtv-smart#2]
Hi. I tried your plugin.
But i get this error (Wrong SmartThings token.)
I have generated several tokens but no one is working.

**Comment by ollo69** [comment]
Hi,

did you follow the guide step by step?
Does the component works without the SmartThings token?
What is your TV model?

Also should help if you have some error from the log and you can post it here.

**Comment by Krocko** [comment]
Hi.
Yes, I followed the guide. 
I have used the Samsung-tizen Plugin previously and that worked.
I have not tested without the token. 

My model is a QE55Q7CGM.

**Comment by ollo69** [comment]
I suppose that the problem is in the process to identify the name and than the ID of the device. I tested it with my TV and it work, but I need to performe additional test with other model, your help is appreciated. Please as first step let me know if you can configure the component leaving the token key blank and if you can see the device info in the device page.

**Comment by Krocko** [comment]
It is working, if i leave the token key blank.

<img width="303" alt="Bildschirmfoto 2020-03-25 um 18 42 37" src="https://user-images.githubusercontent.com/29394115/77568376-d25c4b80-6ec8-11ea-9804-6af7948ec9de.png">

**Comment by ollo69** [comment]
That's fine!

Can you now login to [this page](https://graph-eu01-euwest1.api.smartthings.com/device/list) with your samsung account, select your TV from the devices and attach a screenshot like this:

![image](https://user-images.githubusercontent.com/60491700/77573190-93ca8f00-6ed0-11ea-8743-7a34ce58d7ac.png)

I need to know what you have in the field "label" that I use to identify the TV. I suspect that is empty because you don't set it, anyway I can check "name" if label is empty.

Thanks.

**Comment by Krocko** [comment]
![5BEFE669-E583-4B5D-A76A-00BCCBFBF9CA](https://user-images.githubusercontent.com/29394115/77574400-39cac900-6ed2-11ea-92fc-5892f4c39d40.jpeg)

**Comment by ollo69** [comment]
Thanks.

I suppose that you change the label from SmartThings app, correct?
I make some test, asap I will release a new version fixing SmartThings detection.

**Comment by Krocko** [comment]
I can set a tv name in the smartthings App. I have done this.

**Comment by ollo69** [comment]
Yes, I understand the issue in my assumption. I will fix this in a different way.
Pls wait for new version

**Comment by Krocko** [comment]
Thank you.

**Comment by ollo69** [comment]
Hi,

I published a new release that should fix the problem, until you have only 1 TV registered in SmartThings. I still have to manage the case of multiple TV registered, but now is too late.

Await your feedback.

**Comment by Krocko** [comment]
The integration with the smartthings token is working now. 
But I get the following in the log:
```
Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:586
First occurred: 5:29:01 (1 occurrences) 
Last logged: 5:29:01

Retrieving applications list from TV. It is suggested to define a manual app_list (see component documentation)!!!
```

**Comment by ollo69** [comment]
This is just a log warning at startup that is suggesting to create a manual app_list as explained in readme. It is not an issue and you can ignore it, or you can create the app_list as suggested,
Does everythings work fine?

**Comment by Krocko** [comment]
All is working now.
Thank you very much.
