### ISSUE TITLE
Add prerequisites to the docs (almost none of the extra features is working)

### ISSUE THREAD

**Issue by bcutter** [ollo69/ha-samsungtv-smart#208]
Hi,

I'm using this integration with a Samsung AU8079 TV.
I'm using v0.7.9 (latest available vor my HA Core version).

Problem: Almost none of the [additional features](https://github.com/ollo69/ha-samsungtv-smart#additional-features) is working. Compared to the [original integration](https://www.home-assistant.io/integrations/samsungtv/), there's not a huge difference in terms of functionality. Quick check:
- send keys: ✔
- customized sources list: ❌
- open browser page: ❌
- icons for apps: ❌
- send text: ❌

The only thing I could imagine is: I don't use SmartThings on that TV. https://github.com/ollo69/ha-samsungtv-smart#configuration does note

> ... for using SmartThings (strongly suggested)...

On the other hand, in the https://github.com/ollo69/ha-samsungtv-smart#additional-features section only

> Display logos of TV channels (requires Smartthings enabled) and apps

contains a "requires SmartThings enabled" note.

**Can therefore please someone clarify if SmartThings is needed to make all the additional features work?
Or if this possibly is an actual bug? Or a limitation of that particular Samsung model?**

**Comment by ollo69** [comment]
If you don't use SmartThings, there are no big differences compared with native integration. And not for nothing SmartThings is **strongly suggested**. But if you at least will update your HA version and this integration to last version, you will have the possibility to manage app list from integration options, that is a good feature.
And keep in mind that Samsung API aren't well documented, so this integration is based on test done with available hardware, that in my case is my only Samsung TV. Different models can have different behaviors.

I close this thread because there are nothing to fix.

**Comment by ollo69** [comment]
Ok, I will think about add a more clear sentence in readme to clarify that many integration feature are SmartThings related.

Thanks.
