### ISSUE TITLE
Each time HA restarts, I need to accept access on TV

### ISSUE THREAD

**Issue by gsanhaji** [ollo69/ha-samsungtv-smart#234]
Hi,
Please, each time i restart my HA, i have to grant access to HA on each TV.
Is there a way to automatically grant this access?

**Comment by ollo69** [comment]
Search right option on your TV, you must enable the option to request authorization for external devices only first time

**Comment by gsanhaji** [comment]
I enable it. And it does the same on 3 different TVs.

![IMG_5303](https://user-images.githubusercontent.com/110345517/220471827-d42d585b-829a-4994-b85a-2c599ef2223a.jpg)

**Comment by gsanhaji** [comment]
Hi,
Is there any solution?
I reinstalled everything but still same problem...

**Comment by gsanhaji** [comment]
@seerocode
yes i did.

**Comment by LucasTor** [comment]
Same here, I tried all the steps above but no luck

**Comment by amasolov** [comment]
Same thing for me

**Comment by NicolaiOksen** [comment]
Same for me :(

**Comment by gsanhaji** [comment]
Here is the solution that worked for me:
 1/ Delete the authorization of home assistant on the tv
2/ Delete the integration on home assistant (samsung integration AND samsungsmart integration)
3/ Restart HA
4/ Add your tv on samsung integration
5/ Add your tv on samsungsmart integration

**Comment by ollo69** [comment]
> 4/ Add your tv on samsung integration
> 5/ Add your tv on samsungsmart integration

It is not a good idea configure both integrations, this normally create conflict and is the primary cause of auth request from the TV that will receive continuously 2 requests with different token from the same source!! Because the native integration normally auto-discover the TV in the network, you must `ignore/disable` that integration without configuring, and than start the config flow for `SamsungTVSmart`.
