### ISSUE TITLE
Continuous Authorization Request on TV Screen with Samsung The Frame TV (2022 model)

### ISSUE THREAD

**Issue by StefanoGiu** [ollo69/ha-samsungtv-smart#260]
**Describe the bug**
The integration keeps on sending authorization requests to both the TV I have (Samsung the Frame 85 and 65, model 2022)

**Expected behavior**
Connectivity should be stable

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Core
 - Home Assistant version installed: 2023.6.0
 - Component version installed: v.0.11.6
 - Last know working version: never worked
 - TV model: Samsung the Frame 85/65 model 2022

**Output of HA logs**
2023-07-07 11:13:11.918 WARNING (MainThread) [homeassistant.components.samsungtv] Unexpected ConnectionFailure trying to get remote for 192.168.1.40, please report this issue: ConnectionFailure({'event': 'ms.channel.timeOut'})

```

```

**Additional context**
The TV is connected to the NW switch via ethernet cable and has a stable connection.

**Comment by StefanoGiu** [comment]
I already tried that before, still not working.

**Comment by ronyn77** [comment]
I'm encountering the same issue with my QE77S95C, which happens to be the latest model of 2023. However, this problem doesn't occur with other connected devices, such as my iPhone. The permission was only requested once.

**Comment by ronyn77** [comment]
The solution proposed by Ollo69 appears to have resolved all of my related issues, not just the popups that were occurring upon every restart of Home Assistant. Additionally, I deleted the SmartThings integration in HA. To ensure thoroughness, I also reinitialized the SmartThings API key by first deleting the previous one and then granting access only to the items specified in the guides. Previously, I had granted access to all items. Another step I took was to navigate to the network settings on the TV: Settings -> Network -> Expert Settings, and I enabled "IP Remote." These actions, collectively, seem to have resolved all of my problems.

**Comment by ronyn77** [comment]
> The solution proposed by Ollo69 appears to have resolved all of my related issues, not just the popups that were occurring upon every restart of Home Assistant. Additionally, I deleted the SmartThings integration in HA. To ensure thoroughness, I also reinitialized the SmartThings API key by first deleting the previous one and then granting access only to the items specified in the guides. Previously, I had granted access to all items. Another step I took was to navigate to the network settings on the TV: Settings -> Network -> Expert Settings, and I enabled "IP Remote." These actions, collectively, seem to have resolved all of my problems.

Unfortunatelly after writing this...I found to do not be true at 100%. One thing remains unsolved in my case....I had put the mediaplayer entity of the Tv on the dashboard. Even if the Tv is on, after a while...i cannot tell exactly how much time, it seems to me to do not be the same every time, probably 5 or 10 minutes, the entity shows to be off....to make it work again, I have to turn off the tv using its remote and when I turn it on again with its remote, the mediaplayer entity goes online again, again for a while and then the same issue...while the entity shows it is only I can do everything and everything works. Once on the dashboard it show that it is off, nothing works anymore.....I do not know if it is better to open a new post for this or it could be find a solution also here....

**Comment by Opontios** [comment]
This issue is persisting despite doing everything that is described as a solution in all those issue reports. And it's very annoying first, and second if you don't approve the notification on time, the integration looses control of the TV, so it can't be turned off, for example, when you're leaving home and you have an automation that turns everything off, you see the notification popping up, and you have to go to the TV and approve, else the TV stays on. 
I realize that the TV is not storing the approval of notification, and although you can see Home Assistant among the approved devices, the TV is asking it again. Isn't it anything that can be done to solve this? Else it becomes impossible to use this integration on a regular bases.

**Comment by ronyn77** [comment]
I don't think it's about the integration... It solely depends on the TV's faulty firmware. I experienced the same issue with my S95C. After several resets of the TV and toggling all the notifications in the TV menu on and off, it started working.

**Comment by Opontios** [comment]
> I don't think it's about the integration... It solely depends on the TV's faulty firmware. I experienced the same issue with my S95C. After several resets of the TV and toggling all the notifications in the TV menu on and off, it started working.

Ok, intuitively I can sense that the issue must be with the TV's firmware, but one argument against that is that I have 2 different Samsung models with different firmware versions and different year of manufacture, and it happens on both, and second, why isn't it asking approval for all the other devices connected to the TVs?

**Comment by ronyn77** [comment]
I had the exact same problems with my Samsung S95C initially. It worked for other devices but not for Home Assistant. After resetting and frequently changing the settings, the annoying pop-ups finally stopped. Honestly, I don't remember the exact reason, so it seemed rather random. Please note that you have to disable the notifications and give approval. Also, be aware that if you hard restart Home Assistant, it might prompt you again. If it still doesn’t work, your last resort for turning the TV on and off is to use an external device. In my case, I have a Google Chromecast attached to the TV. With the Google devices in my house, I can control the TV using Google Chromecast. Alternatively, if you use Node-RED, you can create flows to manage this. If you have an Apple TV, I believe you can do the same.

**Comment by ollo69** [comment]
I understand the frustration of people that continuously receive popup notification on the TV, but let me say that the process is very simple:

1) Try first connection with the TV (without a token) -> during this phase the popup is shown on the TV and when the user confirm the token is generated and sent back to the integration
2) The integration store the token in the config entry
3) Next time the integration try to connect, it use the stored token. If the TV consider the token not valid anymore, a new popup is shown and a new token is released, and the integration replace the previous one with the new one.

The reason for which the previous token is not considered valid anymore, can vary, I put here just a couple of cases that I know:

1) The TV is configured to always ask for authorization (and not only the first time) -> in this case the token is not considered valid all the time, popup always appear
2) Other Integrations / software from the same HW try to communicate with the TV (this is the typical case where multiple Samsung TV integration are enabled and configured) -> in this case the TV probably invalidate the token because another integration try to connect with a different one. It is important to have only 1 integration configured, all the others should be disabled / removed. I'm thinking about implement a notification message to alert about another TV integration configured  (eg. the native one, that BTW use auto-discovery and must be ignored!!!).

I do not have any element to understand exactly what happen, one possible option is enable the debug log for integration to analyze the log when token is requested again.
In my case I have a 2022 Samsung TV configured from about 1 year, never received popup after first configuration.

For now I reopen this issue, just to see if someone can provide additional information.

**Comment by ollo69** [comment]
I would add just another think: could somebody test if native integration have the same issue?

**Comment by Opontios** [comment]
> I would add just another think: could somebody test if native integration have the same issue?

Frankly, I was considering the same thing the last days, to install the native integration and test it. The issue is that I started using your integration from the beginning, I never used the native, and never wanted to use it, so it always stayed as "ignored'. (By the way, thanks for all the effort made). 
And of course the "ask for authorization only the first time" setting was always enabled.
I will follow your advice and enable the integration's debug. It must be done in the integration's page, right?

**Comment by ollo69** [comment]
Honestly I would be surprised discovering that native integration do not have the same issue, but in that case I will further investigate in possible difference between the 2 integration.
The real limitation of native integration is that it doesn't use SmartThings and this limit a lot the controls for the TV, especially for the part related to the control and information about sources and channels

**Comment by ollo69** [comment]
> Honestly I would be surprised discovering that native integration do not have the same issue, but in that case I will further investigate in possible difference between the 2 integration. The real limitation of native integration is that it doesn't use SmartThings and this limit a lot the controls for the TV, especially for the part related to the control and information about sources and channels.

> It must be done in the integration's page, right?

Yes, should exist an option "Enable debug tracing" that I think is enough

**Comment by Opontios** [comment]
>     * Disabled polling :( - 
> 
Can you explain what exactly do you mean by that? What polling?

**Comment by felipecrs** [comment]
[Your tips](https://github.com/ollo69/ha-samsungtv-smart/issues/260#issuecomment-1817331053) worked for me. Thanks a ton!

**Comment by MrBlue90** [comment]
Currently experiencing the same issue, however, I might have found a way to resolve it.
Additional to ollo69's recommendations, I did the following:

- Disable polling for new devices in the native Samsung integration: I managed to do so while removing the configured integration.
- Restart Home Assistant: I noticed that HA kept sending permission request, even while both integrations were deleted

**Comment by alberthaff** [comment]
@MrBlue90 Thanks! I can confirm that I've solved the issue by:
- Removing all configured "SamsungTV Smart" devices
- Restart HA

My TV kept showing the permission popup even after i removed the devices. It didn't stop until i restarted HA.
After going through the steps i mentioned above, the connection seems stable.
