### ISSUE TITLE
Add option for update interval

### ISSUE THREAD

**Issue by Final-Hawk** [ollo69/ha-samsungtv-smart#73]
Whenever I update the plugin, i need to go into the files and manually change the update refresh interval. This is because I have automations that run as soon as the TV turns on.

Would it be possible to add a way in the UI to specify the default state update interval?

Thanks for this plugin, its really good!

**Comment by ollo69** [comment]
It is not a good practice allow user to change refresh interval. The value is set to work properly with the integration and should not be changed. You could break HA state machine, and connection with the cloud.

**Comment by Final-Hawk** [comment]
Thanks for the response. That's a shame, so is the plug-in already configured near to the minimum recommended refresh interval? I'm just curious since my hack was working quite well set at 5 seconds

**Comment by ollo69** [comment]
Because some of the feature of this integration are based on cloud polling (SmartThings), going below current refresh rate (15 seconds) is not a good idea. The risk is to reach the limit set by the API and have error during refresh. In any case 5 seconds is a very low refresh rate, consider that the default value in HA for polling refresh is set to 30 seconds.

**Comment by Final-Hawk** [comment]
Fair enough, I'll close this then

**Comment by Final-Hawk** [comment]
Fair enough, I’ll close this issue then.
