### ISSUE TITLE
TV keeps showing Authorisation pop up

### ISSUE THREAD

**Issue by danp2811** [ollo69/ha-samsungtv-smart#84]
My Samsung tv (UE55MU6100) keeps showing the authorisation pop up when powered on, I can’t power on via HA if left for more than 10 minutes or so. Once I allow the control it works fine though. 
Is this known about or is there something wrong with my config?

I’m running HA in docker 

Thanks

**Comment by ollo69** [comment]
Did you configure on the TV to ask authorization "only 1st time"?

**Comment by Jackahack** [comment]
got the same error. and yes i have checked the first time option. also the power button seems inverted.

**Comment by TheStigh** [comment]
Q70R - got the same issue
Also made sure I have chosen "only 1st time".

**Comment by mhoroschun** [comment]
Have you tried disabling the other Samsung Smart TV integration? 

I had the same problem before realizing that I had both running at the same time.

**Comment by danp2811** [comment]
The other one is definitely disabled. Thanks though!

**Comment by TheStigh** [comment]
> 
> 
> Have you tried disabling the other Samsung Smart TV integration?
> 
> I had the same problem before realizing that I had both running at the same time.

Which one, specifically ?

**Comment by ollo69** [comment]
> Which one, specifically ?

Any other, expecially the native one obviosly.



> The other one is definitely disabled. Thanks though!

Please check if in the `.storage` folder exist a file with a name like `samsungtv_smart_<your TV ip>_token` and if the file is not empty.

**Comment by ragaimeena** [comment]
Any resolution??same issue

**Comment by Lepelot** [comment]
> Did you configure on the TV to ask authorization "only 1st time"?

Hello, I am a bit late in this conversation, but I have the same problem. 

First question is where is this "first time only" option, I can't find it. 

My second question is why do I get two different approval requests (ie. not the same requestor)? I generally accept the first one from my HA instance and then everything seems to work fine, but then for some sources, I get a second request from a long string of carracters. 
I assume this is caused by the various trial and errors I did during my initial installation of the samsung intergration, but so far I wasn't able to fix it. 
At this point I would welcome any advise. Thank you.

**Comment by 3raser95** [comment]
I managed to fix this issue on my installation.

The option is in general settings -> external devices -> "one of the sub menus" -> ask for permission setting.
Sorry I'm not at home so can't remember exact menus but I think that should be enough to guide you to the right way.

For me changing the setting initially changed nothing so I had to remove the granted permission for home assistant from the menu below the permission setting then doing a reboot on the TV by pressing and holding the power button until the startup image shows on the TV. After that I got the notification again on the TV, pressed allow and did not get any notifications ever since and everything works great!

**Comment by ollo69** [comment]
To configure external device communication TV must provide a Token to the device, and that be able to reuse authenticated token. For this reason you must set "Ask only first time" in authentication settings, this will allow to receive the token and that reuse the next times without asking. If device was previously authorized but the token is non available on external system (because, for instance, was reconfigured), you need to clean-up all previous authorization on the TV so that token is regenerated.
Because in same case some running apps block the authentication, is a good practice to cold boot the TV before pairing. You can do this with remote on some models, but the simpler solution is to unplug and plug again the power supply.

**Comment by ollo69** [comment]
This integration use polling for status update, and polling interval is 15 second. We cannot lower it or this could impact performance in all HA state machine. Furthermore we need to consider the refresh latency in SmartThings, so 15-20sec delays is normal and cannot be improved.

**Comment by Lepelot** [comment]
Alright, thank you for the explanation. 

Pierre-François Pichery
